
spring.datasource.url=jdbc:mysql://localhost:3306/loja?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.show-sql=true
mercado_pago_sample_access_token=TEST-3924392845806003-040519-4c00925c5a11ea03677c341b380b9b74-192290408
# DESATIVA o restart automático do DevTools (Ele só vai reiniciar se VOCÊ mandar)
spring.devtools.restart.enabled=false

# Se quiser manter apenas o LiveReload (atualizar o navegador sem cair o servidor)
spring.devtools.livereload.enabled=true


spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.cache=false