
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
mercado_pago_sample_access_token=${MP_TOKEN}
spring.jpa.show-sql=true
# DESATIVA o restart automático do DevTools (Ele só vai reiniciar se VOCÊ mandar)
spring.devtools.restart.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gestaoempresarialshark@gmail.com
spring.mail.password=ymxyhuhnetdstref
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Se quiser manter apenas o LiveReload (atualizar o navegador sem cair o servidor)
spring.devtools.livereload.enabled=true


spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true



spring.thymeleaf.cache=false